[project]
name = "intro-ot-csie-exercise-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mofish", email = "a951206b@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
intro-ot-csie-exercise-1 = "intro_ot_csie_exercise_1:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
